# -*- coding: utf-8 -*-
"""
train.py  -  Deepfake Audio Detection (FIXED RETRAINING)
==========================================================

ROOT CAUSE OF BAD ACCURACY:
  Previous run used SYNTHETIC SINE WAVES as "real" audio because
  Common Voice and LJSpeech downloads failed. Real speech MFCCs
  look like TTS speech MFCCs, so the model labelled everything Fake.

FIX:
  1. Use LibriSpeech (open, no login) as REAL human speech
  2. Use gTTS Hindi speech as FAKE (TTS-generated)
  3. Clear old synthetic data before training

IMPORTANT: Delete data/real/ before running if it contains synthetic clips.
"""

import os, sys, warnings, random, shutil
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from tqdm import tqdm
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

sys.path.insert(0, str(Path(__file__).parent))
from utils.preprocess         import preprocess_audio, save_wav, TARGET_SR
from utils.feature_extraction import extract_features_for_cnn
from utils.model              import (DeepfakeAudioCNN, build_cnn_model,
                                      save_model_joblib, DEVICE)

warnings.filterwarnings("ignore")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ─── Config ──────────────────────────────────────────────────────────────────
MAX_REAL   = int(os.getenv("MAX_REAL",   "300"))
MAX_FAKE   = int(os.getenv("MAX_FAKE",   "300"))
EPOCHS     = int(os.getenv("EPOCHS",     "30"))
BATCH_SIZE = int(os.getenv("BATCH_SIZE", "32"))

DATA_DIR   = Path("data")
REAL_DIR   = DATA_DIR / "real"
FAKE_DIR   = DATA_DIR / "fake"
MODEL_PATH = "model.pkl"
PLOT_DIR   = Path("plots")

REAL_DIR.mkdir(parents=True, exist_ok=True)
FAKE_DIR.mkdir(parents=True, exist_ok=True)
PLOT_DIR.mkdir(exist_ok=True)


# =============================================================================
# STEP 0 – Guard: remove any synthetic (non-speech) real clips from last run
# =============================================================================

def _is_synthetic_data() -> bool:
    """
    Detect if data/real/ was generated by the old synthetic fallback
    by checking for a marker file written by this script.
    """
    marker = REAL_DIR / ".synthetic"
    return marker.exists()


def purge_synthetic_real():
    """Delete data/real/ if it only contains synthetic sine waves."""
    if _is_synthetic_data():
        print("[WARN] Purging old SYNTHETIC real clips (they cause bad accuracy).")
        shutil.rmtree(str(REAL_DIR))
        REAL_DIR.mkdir(parents=True, exist_ok=True)
        print("[INFO] data/real/ cleared. Will download real speech now.")
    else:
        existing = sorted(REAL_DIR.glob("real_*.wav"))
        if existing:
            print(f"[INFO] Found {len(existing)} existing real clips (kept).")


def _mark_synthetic():
    """Leave a marker so next run knows these are synthetic."""
    (REAL_DIR / ".synthetic").write_text("synthetic")


# =============================================================================
# STEP 1 – Download REAL human speech
# Priority: LibriSpeech (always free) -> Common Voice -> synthetic (last resort)
# =============================================================================

def _save_clip(arr: np.ndarray, idx: int, out_dir: Path, prefix: str) -> str:
    from utils.preprocess import normalize_waveform, fix_length
    arr = normalize_waveform(arr.astype(np.float32))
    arr = fix_length(arr)
    out = str(out_dir / f"{prefix}_{idx:05d}.wav")
    save_wav(arr, out)
    return out


def _try_librispeech(max_clips: int) -> list:
    """
    LibriSpeech test-clean via HuggingFace (completely open, ~350MB total).
    Uses the 'test' split which is small enough for quick download.
    Audio: 16kHz English read speech from LibriVox audiobooks.
    """
    import librosa
    from datasets import load_dataset
    saved, idx = [], 0
    print("[INFO] Downloading LibriSpeech test-clean (real human speech)...")
    print("       This is legitimate human speech - perfect for 'Real' class.")

    # Try multiple configurations
    configs_to_try = [
        ("librispeech_asr", "clean", "test"),
        ("librispeech_asr", "clean", "validation"),
        ("librispeech_asr", "clean", "train.100"),
        ("openslr/librispeech_asr", "clean", "test"),
    ]

    ds = None
    for dataset_id, config, split in configs_to_try:
        try:
            ds = load_dataset(dataset_id, config,
                              split=split, streaming=True, trust_remote_code=False)
            print(f"[INFO] Connected to {dataset_id} ({config}/{split})")
            break
        except Exception as e:
            print(f"  [WARN] {dataset_id}/{config}/{split}: {e}")

    if ds is None:
        raise RuntimeError("All LibriSpeech sources failed.")

    for sample in tqdm(ds, total=max_clips, desc="LibriSpeech-real"):
        if idx >= max_clips:
            break
        try:
            arr = np.array(sample["audio"]["array"], dtype=np.float32)
            sr  = sample["audio"]["sampling_rate"]
            if sr != TARGET_SR:
                arr = librosa.resample(arr, orig_sr=sr, target_sr=TARGET_SR)
            path = _save_clip(arr, idx, REAL_DIR, "real")
            saved.append(path)
            idx += 1
        except Exception as e:
            pass  # skip bad samples silently
    return saved


def _try_common_voice(max_clips: int) -> list:
    """Common Voice Hindi (needs HuggingFace login)."""
    import librosa
    from datasets import load_dataset
    saved, idx = [], 0
    print("[INFO] Trying Mozilla Common Voice 13 Hindi...")
    ds = load_dataset("mozilla-foundation/common_voice_13_0", "hi",
                      split="train", streaming=True, trust_remote_code=False)
    for sample in tqdm(ds, total=max_clips, desc="CommonVoice-real"):
        if idx >= max_clips:
            break
        try:
            arr = np.array(sample["audio"]["array"], dtype=np.float32)
            sr  = sample["audio"]["sampling_rate"]
            if sr != TARGET_SR:
                arr = librosa.resample(arr, orig_sr=sr, target_sr=TARGET_SR)
            saved.append(_save_clip(arr, idx, REAL_DIR, "real"))
            idx += 1
        except Exception:
            pass
    return saved


def _try_peoples_speech(max_clips: int) -> list:
    """
    People's Speech - Apache 2.0 licensed, no login needed.
    ~30,000 hours of English speech.
    """
    import librosa
    from datasets import load_dataset
    saved, idx = [], 0
    print("[INFO] Trying MLCommons People's Speech...")
    ds = load_dataset("MLCommons/peoples_speech", "clean",
                      split="train", streaming=True, trust_remote_code=False)
    for sample in tqdm(ds, total=max_clips, desc="PeoplesSpeech-real"):
        if idx >= max_clips:
            break
        try:
            arr = np.array(sample["audio"]["array"], dtype=np.float32)
            sr  = sample["audio"]["sampling_rate"]
            if sr != TARGET_SR:
                arr = librosa.resample(arr, orig_sr=sr, target_sr=TARGET_SR)
            saved.append(_save_clip(arr, idx, REAL_DIR, "real"))
            idx += 1
        except Exception:
            pass
    return saved


def _generate_synthetic_real_LAST_RESORT(max_clips: int) -> list:
    """
    !! LAST RESORT ONLY !!
    This produces a BAD model. If you land here, fix your internet
    or provide a HuggingFace token. The model WILL be inaccurate.
    """
    print("=" * 60)
    print("!! WARNING: USING SYNTHETIC DATA !!")
    print("!! The resulting model WILL classify real speech as Fake !!")
    print("!! Please provide internet access and re-run. !!")
    print("=" * 60)
    from utils.preprocess import CLIP_SAMPLES, normalize_waveform
    saved = []
    rng = np.random.default_rng(SEED)
    for idx in tqdm(range(max_clips), desc="Synth-real [BAD]"):
        t   = np.linspace(0, 3.0, CLIP_SAMPLES)
        f0  = rng.uniform(100, 300)
        sig = sum(np.sin(2 * np.pi * k * f0 * t) / k for k in range(1, 8))
        sig += 0.05 * rng.standard_normal(CLIP_SAMPLES)
        out = str(REAL_DIR / f"real_{idx:05d}.wav")
        save_wav(normalize_waveform(sig.astype(np.float32)), out)
        saved.append(out)
    _mark_synthetic()   # mark so next run purges this
    return saved


def download_real_audio() -> list:
    print("\n" + "=" * 60)
    print("STEP 1 - Acquiring REAL Human Speech Audio")
    print("=" * 60)

    # Check cache (only if not synthetic)
    if not _is_synthetic_data():
        existing = sorted(REAL_DIR.glob("real_*.wav"))
        if len(existing) >= MAX_REAL:
            print(f"[INFO] {len(existing)} cached real clips found. Skipping download.")
            return [str(p) for p in existing[:MAX_REAL]]

    # Try LibriSpeech first (best free option, no login needed)
    for fn in [_try_librispeech, _try_peoples_speech, _try_common_voice]:
        try:
            paths = fn(MAX_REAL)
            if len(paths) >= 20:    # need at least 20 real clips
                print(f"[INFO] Got {len(paths)} real human speech clips.")
                return paths
        except Exception as e:
            print(f"[WARN] {fn.__name__} failed: {e}")
            print(f"       Trying next source...")

    print("[ERROR] All real speech sources failed. Using synthetic fallback.")
    print("        MODEL ACCURACY WILL BE POOR.")
    return _generate_synthetic_real_LAST_RESORT(MAX_REAL)


# =============================================================================
# STEP 2 – Generate FAKE audio (TTS / synthesised)
# =============================================================================

SENTENCES = [
    "Hello, this is a test of text to speech synthesis.",
    "The weather today is sunny and warm.",
    "I enjoy listening to music in the evening.",
    "Please verify the authenticity of this audio recording.",
    "Artificial intelligence is changing the world rapidly.",
    "Deep learning models can recognize speech patterns.",
    "This sentence was generated by a computer program.",
    "The quick brown fox jumps over the lazy dog.",
    "Technology has made communication easier than ever before.",
    "Scientists are working on new advances in audio detection.",
    "Voice cloning technology poses security risks.",
    "Natural language processing improves every year.",
    "Machine learning can detect anomalies in audio signals.",
    "Computer generated speech has become very realistic.",
    "Researchers are developing methods to identify fake audio.",
    "The model was trained on thousands of audio samples.",
    "Feature extraction is an important step in audio analysis.",
    "Convolutional neural networks excel at pattern recognition.",
    "Audio deepfakes can be used for misinformation.",
    "Detection systems must keep pace with generation systems.",
]

HINDI_SENTENCES = [
    "Namaste, mera naam Ram hai.",
    "Aaj mausam bahut accha hai.",
    "Bharat ek mahan desh hai.",
    "Main dilli mein rehta hoon.",
    "Yeh ek parikshan vakya hai.",
    "Sangeet sunna mujhe pasand hai.",
    "Hum sab milkar kaam karenge.",
    "Bachche school jaate hain.",
    "Kya aap meri madad kar sakte hain?",
    "Aaj pariksha ka parinaam aayega.",
]


def _generate_fake_gtts(n: int, lang: str = 'en') -> list:
    """Generate TTS audio with gTTS."""
    from gtts import gTTS
    import tempfile
    saved = []
    pool = SENTENCES if lang == 'en' else HINDI_SENTENCES
    print(f"[INFO] Generating {n} TTS clips with gTTS (lang={lang})...")

    for idx in tqdm(range(n), desc=f"gTTS-{lang}"):
        out = str(FAKE_DIR / f"fake_{idx:05d}.wav")
        if os.path.exists(out):
            saved.append(out)
            continue
        text = pool[idx % len(pool)]
        try:
            tts = gTTS(text=text, lang=lang, slow=False)
            with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
                tmp_path = tmp.name
            tts.save(tmp_path)
            wav = preprocess_audio(tmp_path)
            if wav is not None:
                save_wav(wav, out)
                saved.append(out)
            try:
                os.unlink(tmp_path)
            except Exception:
                pass
        except Exception as e:
            print(f"  [WARN] gTTS sample {idx}: {e}")
    return saved


def _generate_synthetic_fake(n: int) -> list:
    """Offline fallback: FM chirp signals as fake-class baseline."""
    print("[WARN] gTTS offline - generating synthetic chirp fake audio.")
    from utils.preprocess import CLIP_SAMPLES, normalize_waveform
    saved = []
    rng = np.random.default_rng(SEED + 1)
    for idx in tqdm(range(n), desc="Synth-fake"):
        t  = np.linspace(0, 3.0, CLIP_SAMPLES)
        f0 = rng.uniform(200, 600)
        sig = np.sin(2 * np.pi * (f0 + 80 * t) * t)
        sig += 0.02 * rng.standard_normal(CLIP_SAMPLES)
        out = str(FAKE_DIR / f"fake_{idx:05d}.wav")
        save_wav(normalize_waveform(sig.astype(np.float32)), out)
        saved.append(out)
    return saved


def generate_fake_audio(n: int = MAX_FAKE) -> list:
    print("\n" + "=" * 60)
    print("STEP 2 - Generating Fake (TTS) Audio")
    print("=" * 60)
    existing = sorted(FAKE_DIR.glob("fake_*.wav"))
    if len(existing) >= n:
        print(f"[INFO] {len(existing)} cached fake clips found.")
        return [str(p) for p in existing[:n]]
    # Try English first (more reliable gTTS), then Hindi
    for lang in ['en', 'hi']:
        try:
            paths = _generate_fake_gtts(n, lang=lang)
            if len(paths) >= n // 2:
                return paths
        except Exception as e:
            print(f"[WARN] gTTS {lang} failed: {e}")
    return _generate_synthetic_fake(n)


# =============================================================================
# STEP 3 – Feature Extraction
# =============================================================================

def _extract(fp: str):
    try:
        wav = preprocess_audio(fp)
        return None if wav is None else extract_features_for_cnn(wav)
    except Exception as e:
        print(f"  [WARN] {fp}: {e}")
        return None


def build_dataset(real_paths: list, fake_paths: list):
    print("\n" + "=" * 60)
    print("STEP 3 - Extracting MFCC Features")
    print("=" * 60)
    X_list, y_list = [], []
    print(f"[INFO] Extracting from {len(real_paths)} real clips ...")
    for fp in tqdm(real_paths, desc="Real MFCC"):
        feat = _extract(fp)
        if feat is not None:
            X_list.append(feat)
            y_list.append(0)   # real = 0
    print(f"[INFO] Extracting from {len(fake_paths)} fake clips ...")
    for fp in tqdm(fake_paths, desc="Fake MFCC"):
        feat = _extract(fp)
        if feat is not None:
            X_list.append(feat)
            y_list.append(1)   # fake = 1
    X = np.array(X_list, dtype=np.float32)
    y = np.array(y_list, dtype=np.float32)
    real_n = int((y == 0).sum())
    fake_n = int((y == 1).sum())
    print(f"[INFO] Dataset: X={X.shape}, Real={real_n}, Fake={fake_n}")
    if real_n < 10 or fake_n < 10:
        raise RuntimeError(f"Too few samples: Real={real_n}, Fake={fake_n}. Check data sources.")
    return X, y


# =============================================================================
# STEP 4 – Train CNN with better regularisation
# =============================================================================

def train_model(X: np.ndarray, y: np.ndarray):
    print("\n" + "=" * 60)
    print("STEP 4 - Training CNN (PyTorch)")
    print("=" * 60)

    from sklearn.model_selection import train_test_split

    # (N, 40, 300, 1) -> (N, 1, 40, 300)
    Xp = X[:, :, :, 0][:, np.newaxis, :, :].astype(np.float32)
    yp = y.astype(np.float32).reshape(-1, 1)

    Xt, Xtmp, yt, ytmp = train_test_split(
        Xp, yp, test_size=0.30, random_state=SEED, stratify=yp)
    Xv, Xte, yv, yte = train_test_split(
        Xtmp, ytmp, test_size=0.50, random_state=SEED, stratify=ytmp)

    def mk_loader(Xa, ya, shuffle=True):
        ds = TensorDataset(torch.from_numpy(Xa), torch.from_numpy(ya))
        return DataLoader(ds, batch_size=BATCH_SIZE, shuffle=shuffle,
                          num_workers=0, pin_memory=False)

    tr_loader  = mk_loader(Xt,  yt,  shuffle=True)
    val_loader = mk_loader(Xv,  yv,  shuffle=False)
    print(f"[INFO] Train={len(Xt)}, Val={len(Xv)}, Test={len(Xte)}")

    model, optim, _ = build_cnn_model(learning_rate=5e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(optim, T_max=EPOCHS)

    # Weighted BCE for class balance
    n0 = float((yt == 0).sum())
    n1 = float((yt == 1).sum())
    pos_w = torch.tensor([n0 / max(n1, 1)]).to(DEVICE)
    loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_w)

    # Use raw logits (remove sigmoid for BCEWithLogitsLoss)
    model.classifier[-1] = nn.Identity()

    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}
    best_val, patience_cnt = float("inf"), 0
    PATIENCE = 8

    for epoch in range(1, EPOCHS + 1):
        # Train
        model.train()
        tr_loss, tr_ok, tr_n = 0.0, 0, 0
        for Xb, yb in tr_loader:
            Xb, yb = Xb.to(DEVICE), yb.to(DEVICE)
            optim.zero_grad()
            logits = model(Xb)
            loss   = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optim.step()
            tr_loss += loss.item() * len(Xb)
            tr_ok   += ((torch.sigmoid(logits) >= 0.5).float() == yb).sum().item()
            tr_n    += len(Xb)
        tr_loss /= tr_n; tr_acc = tr_ok / tr_n

        # Validate
        model.eval()
        vl, vok, vn = 0.0, 0, 0
        with torch.no_grad():
            for Xb, yb in val_loader:
                Xb, yb = Xb.to(DEVICE), yb.to(DEVICE)
                logits  = model(Xb)
                vl     += loss_fn(logits, yb).item() * len(Xb)
                vok    += ((torch.sigmoid(logits) >= 0.5).float() == yb).sum().item()
                vn     += len(Xb)
        vl /= vn; val_acc = vok / vn
        sched.step()

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(vl)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(val_acc)
        print(f"  Epoch {epoch:3d}/{EPOCHS} | "
              f"loss {tr_loss:.4f}  acc {tr_acc*100:.1f}% | "
              f"val_loss {vl:.4f}  val_acc {val_acc*100:.1f}%")

        if vl < best_val - 1e-4:
            best_val = vl; patience_cnt = 0
            torch.save(model.state_dict(), "best_cnn.pt")
        else:
            patience_cnt += 1
            if patience_cnt >= PATIENCE:
                print(f"[INFO] Early stopping at epoch {epoch}.")
                break

    model.load_state_dict(torch.load("best_cnn.pt", map_location=DEVICE))
    model.eval()
    model.classifier[-1] = nn.Sigmoid()   # restore for inference
    return model, history, Xte, yte


# =============================================================================
# STEP 5 – Evaluate
# =============================================================================

def evaluate_model(model, X_test: np.ndarray, y_test: np.ndarray) -> None:
    from sklearn.metrics import (accuracy_score, precision_score,
                                 recall_score, f1_score, confusion_matrix,
                                 classification_report)
    import seaborn as sns

    print("\n" + "=" * 60)
    print("STEP 5 - Evaluation on Held-Out Test Set")
    print("=" * 60)

    model.eval()
    Xp = torch.from_numpy(X_test).to(DEVICE)
    with torch.no_grad():
        probs = model(Xp).cpu().numpy().ravel()
    y_pred = (probs >= 0.5).astype(int)
    y_true = y_test.astype(int).ravel()

    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec  = recall_score(y_true, y_pred, zero_division=0)
    f1   = f1_score(y_true, y_pred, zero_division=0)

    print(f"\n{'-'*45}")
    print(f"  Accuracy  : {acc  * 100:.2f} %")
    print(f"  Precision : {prec * 100:.2f} %")
    print(f"  Recall    : {rec  * 100:.2f} %")
    print(f"  F1-Score  : {f1   * 100:.2f} %")
    print(f"{'-'*45}\n")
    print(classification_report(y_true, y_pred, target_names=["Real", "Fake"]))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["Real", "Fake"],
                yticklabels=["Real", "Fake"])
    plt.title("Confusion Matrix")
    plt.ylabel("True Label"); plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.savefig(str(PLOT_DIR / "confusion_matrix.png"), dpi=150)
    print(f"[INFO] Saved plots/confusion_matrix.png")


def plot_history(history: dict) -> None:
    fig, ax = plt.subplots(1, 2, figsize=(12, 4))
    ax[0].plot(history["train_acc"],  label="Train"); ax[0].plot(history["val_acc"],  label="Val")
    ax[0].set_title("Accuracy"); ax[0].legend(); ax[0].grid(alpha=0.3)
    ax[1].plot(history["train_loss"], label="Train"); ax[1].plot(history["val_loss"], label="Val")
    ax[1].set_title("Loss"); ax[1].legend(); ax[1].grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(str(PLOT_DIR / "training_curves.png"), dpi=150)
    print(f"[INFO] Saved plots/training_curves.png")


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("  Deepfake Audio Detection - RETRAIN (Fixed)")
    print(f"  Device: {DEVICE} | MAX_REAL={MAX_REAL} MAX_FAKE={MAX_FAKE}")
    print(f"  Epochs: {EPOCHS} | Batch: {BATCH_SIZE}")
    print("=" * 60)

    # CRITICAL: Remove synthetic clips if they exist
    purge_synthetic_real()

    real_paths = download_real_audio()
    fake_paths = generate_fake_audio(n=MAX_FAKE)

    if not real_paths or not fake_paths:
        raise RuntimeError("No audio data available.")

    n = min(len(real_paths), len(fake_paths))
    real_paths, fake_paths = real_paths[:n], fake_paths[:n]
    print(f"\n[INFO] Balanced: {n} real + {n} fake = {2*n} total clips")

    # Clear cached features (force re-extraction with new data)
    for f in ["X.npy", "y.npy"]:
        if Path(f).exists():
            Path(f).unlink()

    X, y = build_dataset(real_paths, fake_paths)
    np.save("X.npy", X)
    np.save("y.npy", y)
    print("[INFO] Features cached -> X.npy, y.npy")

    model, history, X_test, y_test = train_model(X, y)

    evaluate_model(model, X_test, y_test)
    plot_history(history)

    from sklearn.preprocessing import StandardScaler
    save_model_joblib(model, StandardScaler(), path=MODEL_PATH)

    print("\n" + "=" * 60)
    print("  Retraining complete! model.pkl updated.")
    print("  Restart server:  python app.py")
    print("=" * 60 + "\n")
